// Deal a single oversized master pool into N unique, near-equal buckets.
//
// The master pool is generated by the REAL engine (window.genDraftPool in the
// game file) so ratings/fees/skills stay engine-consistent — this module only
// PARTITIONS it into disjoint per-manager buckets.
//
// A pure snake (0,1,..,N-1,N-1,..,0,..) balances perfectly only when the pool is
// a multiple of 2N; otherwise the remainder tail clusters the top leftovers in a
// few buckets. We instead process players high→low and place each into the
// not-yet-full bucket with the LOWEST running rating total (size capped at
// ceil(total/N)). This is the LPT partition heuristic: it keeps bucket SIZES
// within 1 of each other AND drives the average-rating spread to near zero for
// any pool size — a strict generalization of the snake.
//
// Plain JS so it runs unchanged in Node tests and Deno Edge Functions.

/** Deal `players` into `n` disjoint, size-balanced, rating-balanced buckets. */
export function snakeDeal(players, n) {
  if (n < 1) throw new Error("need at least 1 bucket");
  const sorted = [...players].sort((a, b) => (b.rating - a.rating) || cmpName(a, b));
  const cap = Math.ceil(sorted.length / n);      // max players per bucket (±1 sizes)
  const buckets = Array.from({ length: n }, () => []);
  const sums = new Array(n).fill(0);
  for (const p of sorted) {
    let best = -1;
    for (let i = 0; i < n; i++) {
      if (buckets[i].length >= cap) continue;
      if (best < 0 || sums[i] < sums[best]) best = i;   // lowest running total wins
    }
    buckets[best].push(p);
    sums[best] += (p.rating || 0);
  }
  return buckets;
}

function cmpName(a, b) {
  return String(a.name) < String(b.name) ? -1 : String(a.name) > String(b.name) ? 1 : 0;
}

/** Average rating of a bucket (0 if empty). */
export function bucketAvg(bucket) {
  if (!bucket.length) return 0;
  return bucket.reduce((s, p) => s + (p.rating || 0), 0) / bucket.length;
}

/** Quality report used by tests + the founder UI: counts, avg spread, uniqueness. */
export function dealReport(buckets) {
  const avgs = buckets.map(bucketAvg);
  const sizes = buckets.map((b) => b.length);
  const names = buckets.flatMap((b) => b.map((p) => p.name));
  const uniqueNames = new Set(names).size;
  const mean = avgs.reduce((a, b) => a + b, 0) / (avgs.length || 1);
  return {
    n: buckets.length,
    sizes,
    sizeSpread: Math.max(...sizes) - Math.min(...sizes),
    avgs: avgs.map((a) => Math.round(a)),
    avgSpread: Math.round(Math.max(...avgs) - Math.min(...avgs)),
    avgSpreadPct: mean ? (Math.max(...avgs) - Math.min(...avgs)) / mean : 0,
    totalPlayers: names.length,
    uniquePlayers: uniqueNames,
    allUnique: uniqueNames === names.length,
  };
}
